name: Build AutismOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          nasm \
          xorriso \
          grub-pc-bin \
          grub-common \
          genisoimage \
          build-essential \
          libc6-dev \
          gcc-multilib \
          libc6-dev-i386 \
          mtools


    - name: Build AutismOS
      run: make

    - name: Upload autismos.iso as artifact
      uses: actions/upload-artifact@v2
      with:
        name: autismos.iso
        path: autismos.iso