name: Build AutismOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          nasm \
          xorriso \
          grub-pc-bin \
          grub-common \
          genisoimage \
          build-essential

    - name: Build AutismOS
      run: make
